//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW0505
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Order = new HashSet<Order>();
        }

        public int ID { get; set; }
        public string NAME { get; set; }
        public string COUNTRY { get; set; }
        public int AGE { get; set; }

        public Customer(int iD, string nAME, string cOUNTRY, int aGE)
        {
            ID = iD;
            NAME = nAME;
            COUNTRY = cOUNTRY;
            AGE = aGE;
        }
      
            



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        
    }
}
