//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW0505
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int CUSTOMER_ID { get; set; }
        public int PRICE { get; set; }
        public int DATE { get; set; }

        public Order(int iD, int cUSTOMER_ID, int pRICE, int dATE)
        {
            ID = iD;
            CUSTOMER_ID = cUSTOMER_ID;
            PRICE = pRICE;
            DATE = dATE;           
        }

        public Order()
        {
        }

        public virtual Customer Customer { get; set; }
    }
}
